# Generated by Django 3.2.25 on 2024-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/drgepxrpe/image/upload/v1711723599/default_profile_vs0i8n.jpg', upload_to='images/'),
        ),
    ]
